apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.30.1-10.0.30.254
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: home-pool-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - home-pool
