apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pihole
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: ingress-nginx
    - name: metallb
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/pihole
  prune: true
  wait: true
